void objArrClear();
void moveBall(float x, float y);
void setCursor(short x, short y);
int objHitBrick(TObj ball);
void showMenu();
int objHitDigit(TObj ball);
bool checkFaild();
TObj objCreate(float x, float y, float a, float spd, char chr);
void objPut(TObj obj);
void correctAngle(float* a);
void objMove(TObj* obj);
void objWorkUpgrade(TObj* obj);
void objWorkBullet(TObj* obj);
void objWork(TObj* obj);
void objArrAdd(TObj obj);
void objArrDelPos(int pos);
void objArrWork(bool ballFaild);
void objArrPut();
void objArrClear();
void initBall();
void putBall();
void objChanceCreateRandomUpgradeObj(float x, float y);
void autoMoveBall();
void initRacket();
void timerFireMod();
void putRacket();
void drawBrick(int x, int y);
void lvlMapPuzzile();
void lvlMapInit();
void lvlMapPut();
void show();
void moveRacket(int x);
void showPreview();
int lvlMapBrickCount();
void checkWin();
void ballWork();
void racketShout();
void racketWork();
void showInstruction();
void showInfo();
void showMenu();